#!/bin/sh
#
# Copyright (c) 2014-2015 Michael Shafae.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# The name of Michael Shafae may not be used to endorse or promote products
# derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER "AS IS" AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER LICENSE.md
#
# $Id: ubuntu_cdev.sh 5484 2015-01-25 20:43:15Z mshafae $
#

backup_file ()
{
  DATE=`date +"%Y%m%d-%S"`
  NAME=${1}
  NEWNAME=${NAME}-${DATE}.og
  echo "Copying ${NAME} to ${NEWNAME}"
  cp "$NAME" "${NEWNAME}"
}

os_update ()
{
  apt-get --yes update
  apt-get --yes upgrade
}

pkg_defaults ()
{
  apt-get --yes install emacs24-lucid subversion zsh git \
  curl sqlite3 lynx graphviz libssl-dev linux-headers-generic \
  build-essential dkms
}

pkg_cdev ()
{
  apt-get --yes install gobjc++ gobjc g++ clang \
  cscope cmake autoconf automake libglib2.0-dev \
  libsdl2-dev libgtest-dev

}

build_gtest ()
{
  # Build gtest static libraries
  BUILDDIR="/tmp/gtestbuild"
  DESTROOT="/usr/local/"
  CWD=`pwd`
  mkdir -p ${BUILDDIR}
  cd ${BUILDDIR}
  cmake -DCMAKE_BUILD_TYPE=RELEASE /usr/src/gtest/
  make
  install -o root -g root -m 644 libgtest.a ${DESTROOT}/lib
  install -o root -g root -m 644 libgtest_main.a ${DESTROOT}/lib
}

misc_gitignore ()
{
  BASE="/opt/local/share/github/"
  CWD=`pwd`
  mkdir -p ${BASE}
  cd ${BASE}
  git clone --depth=1 https://github.com/github/gitignore.git
  cd ${CWD}
}

ID=`id -u`
if [ ${ID} -ne 0 ]; then
        echo "You need to be root to run this script."
        exit 1
fi

os_update
pkg_defaults
pkg_cdev
build_gtest
misc_gitignore
